message(STATUS "QtSsh subdir: ${CMAKE_CURRENT_LIST_DIR}")
set(BUILD_STATIC ON)
add_subdirectory(${CMAKE_CURRENT_LIST_DIR})
include_directories(${CMAKE_CURRENT_LIST_DIR}/qtssh)

if(NOT WITH_SSH_LIBRARIES)
    find_package(PkgConfig REQUIRED)
    pkg_search_module(SSH2 REQUIRED libssh2)
endif(NOT WITH_SSH_LIBRARIES)
set(QTSSH_LIBRARIES QtSsh ${SSH2_LIBRARIES})
